### ISSUE TITLE
False positive?

### ISSUE THREAD

**Issue by ploeh** [hedgehogqa/fsharp-hedgehog#112]
I'm currently working with my [convex hull](https://github.com/ploeh/Hull) F# example code base, and I was adding an addition operator (`+`) to add two convex hulls together. Since I wanted to demonstrate that hulls are monoids, I wrote this Hedgehog property:

```fsharp
[<Fact>]
let ``Hull addition is associative`` () = Property.check <| property {
    let! (x, y, z) =
        Range.linearBounded ()
        |> Gen.int
        |> Gen.tuple
        |> Gen.list (Range.linear 0 100)
        |> Gen.tuple3
    return (hull x + hull y) + hull z = hull x + (hull y + hull z) }
```

Much to my surprise, this property fails:

```
Test 'Ploeh.Geometry.Tests.Hull addition is associative' failed: Hedgehog.FailedException : *** Failed! Falsifiable (after 52 tests and 81 shrinks):
([(0, 0)], [(2283, 43707)], [(50767, 1); (14548, 1)])

	at Hedgehog.ReportModule.tryRaise(Report report)
	at Hedgehog.PropertyModule.check(Property`1 p)
	C:\Users\mark\Documents\Katas\Hull\Geometry.Tests\GeometryTests.fs(79,0): at Ploeh.Geometry.Tests.Hull addition is associative()
```

Trying to understand the problem, I sent my convex hull code to F# Interactive, and copied the repro data:

```
> let (x, y, z) = ([(0, 0)], [(2283, 43707)], [(50767, 1); (14548, 1)]);;

val z : (int * int) list = [(50767, 1); (14548, 1)]
val y : (int * int) list = [(2283, 43707)]
val x : (int * int) list = [(0, 0)]

> (hull x + hull y) + hull z = hull x + (hull y + hull z);;
val it : bool = true
```

As you can see, I defined `x`, `y`, and `z` as reported in the repro, but when I then evaluate the assertion, it returns `true`.

What am I doing wrong?

Or is this a false positive?

**Comment by moodmosaic** [comment]
How does a rough version of `(+)` looks like?

**Comment by ploeh** [comment]
```fsharp
let inline (+) (Hull x) (Hull y) = hull (x @ y)
```

This uses a type I added, which isn't in the publicly available GitHub repro:

```fsharp
type Hull<'a> = Hull of ('a * 'a) list
```

**Comment by moodmosaic** [comment]
Thank you. I guess, I also have to return `Hull` from the `hull` function (?)

```diff
-points |> List.sortWith cmp |> Seq.distinct |> Seq.toList |> hullPoints []
+points |> List.sortWith cmp |> Seq.distinct |> Seq.toList |> hullPoints [] |> Hull
```

**Comment by ploeh** [comment]
Yes, here's the updated `hull` function:

```fsharp
let inline hull points =
    let compareLexigraphic (x1, y1) (x2, y2) = compare (y1, x1) (y2, x2)

    let comparePolar p0 p1 p2 = turn p0 p1 p2 |> int

    let tryDiscard points =
        let rec tryDiscardImp acc = function
            | [p1; p2; p3] when turn p1 p2 p3 = Direction.Right ->
                p3 :: p1 :: acc
            | [p1; p2; p3] -> p3 :: p2 :: p1 :: acc
            | p :: ps -> tryDiscardImp (p :: acc) ps
            | [] -> acc
        let newPoints = tryDiscardImp [] points |> List.rev
        if newPoints.Length <> points.Length
        then Some newPoints
        else None

    let rec discardFrom candidates =
        match tryDiscard candidates with
        | Some newCandidates -> discardFrom newCandidates
        | None -> candidates

    let rec hullPoints candidates = function
        | [] -> candidates
        | p :: tail -> hullPoints (discardFrom (candidates @ [p])) tail

    if List.isEmpty points
    then Hull.identity
    else
        let p0 = points |> List.sortWith compareLexigraphic |> List.head
        let cmp p1 p2 =    
            match comparePolar p0 p1 p2 with
            | 0 -> compareLexigraphic p1 p2
            | x -> x

        points
        |> List.sortWith cmp
        |> Seq.distinct
        |> Seq.toList
        |> hullPoints []
        |> Hull
```

I also had to handle empty lists.

**Comment by moodmosaic** [comment]
Hmm... On my machine both the test and the evaluation of the expression (in F# Interactive) fail:

```f#
[<Fact>]
let ``Hull addition is associative`` () = Property.check <| property {
    let! (x, y, z) =
        Range.linearBounded ()
        |> Gen.int
        |> Gen.tuple
        |> Gen.list (Range.linear 0 100)
        |> Gen.tuple3

    return (hull x + hull y) + hull z = hull x + (hull y + hull z) }
```

```
Test 'addition is associative' failed:
  Hedgehog.FailedException:
    *** Failed! Falsifiable (after 3 tests and 226 shrinks):
      ([(-7465900, -5342129); (26344450, -36906369)], [(93, -1360)], [(728, -2396)])
```

Now, if I go to F# Interactive:

```f#
> let (x, y, z) =  ([(-7465900, -5342129); (26344450, -36906369)], [(93, -1360)], [(728, -2396)]);;
val z : (int * int) list = [(728, -2396)]
val y : (int * int) list = [(93, -1360)]
val x : (int * int) list = [(-7465900, -5342129); (26344450, -36906369)]

> (hull x + hull y) + hull z = hull x + (hull y + hull z);;
val it : bool = false

> 
```

---

Based on above discussion, here's how I was able to modify the `Geometry` module:

```diff
diff --git a/Geometry/Geometry.fs b/Geometry/Geometry.fs
index e15d7ef..b5b7da5 100644
--- a/Geometry/Geometry.fs
+++ b/Geometry/Geometry.fs
@@ -8,17 +8,13 @@ let inline turn (x1, y1) (x2, y2) (x3, y3) =
     elif prod < LanguagePrimitives.GenericZero then Direction.Right
     else Direction.Straight
 
+type Hull<'a> = Hull of ('a * 'a) list
+  
 let inline hull points =
     let compareLexigraphic (x1, y1) (x2, y2) = compare (y1, x1) (y2, x2)
 
     let comparePolar p0 p1 p2 = turn p0 p1 p2 |> int
 
-    let p0 = points |> List.sortWith compareLexigraphic |> List.head
-    let cmp p1 p2 =    
-        match comparePolar p0 p1 p2 with
-        | 0 -> compareLexigraphic p1 p2
-        | x -> x
-
     let tryDiscard points =
         let rec tryDiscardImp acc = function
             | [p1; p2; p3] when turn p1 p2 p3 = Direction.Right ->
@@ -40,4 +36,20 @@ let inline hull points =
         | [] -> candidates
         | p :: tail -> hullPoints (discardFrom (candidates @ [p])) tail
 
-    points |> List.sortWith cmp |> Seq.distinct |> Seq.toList |> hullPoints []
\ No newline at end of file
+    if List.isEmpty points
+    then [] |> Hull
+    else
+        let p0 = points |> List.sortWith compareLexigraphic |> List.head
+        let cmp p1 p2 =    
+            match comparePolar p0 p1 p2 with
+            | 0 -> compareLexigraphic p1 p2
+            | x -> x
+
+        points
+        |> List.sortWith cmp
+        |> Seq.distinct
+        |> Seq.toList
+        |> hullPoints []
+        |> Hull
+    
+let inline (+) (Hull x) (Hull y) = hull (x @ y)
```

**Comment by moodmosaic** [comment]
So, if the evaluation of the expression in F# Interactive fails, maybe there's some weird addition/overflow bug in the Geometry module?

I haven't looked closely (yet) to the Geometry's module `hull` function.

**Comment by ploeh** [comment]
It's most likely an integer overflow problem. The `hull` function _does_ calculate a cross product, and that could easily overflow.

This hypothesis is corroborated by the following experiment. I changed `Range.linearBounded ()` to `Range.linear -10000 10000`, and the problem went away. If I expand the range to `Range.linear -100000 100000` it starts failing. This makes sense, because `10000 * 10000` is within the bounds of `int`, while `100000 * 100000` overflows.

What really confused me was that I couldn't reproduce the issue in FSI. @moodmosaic, your counter-example _does_ reproduce in my FSI, but all the counter-examples my own machine created didn't. I'm not sure I can explain that, but I'm going to close the issue.

Thank you for your help 👍

**Comment by moodmosaic** [comment]
Happy to help!

Yes, `Range.linearBounded ()` uses the full range of the data type:

```f#
> Range.bounds 99 <| (Range.linearBounded () : Range<sbyte>);;
val it : sbyte * sbyte = (-128y, 127y)

> Range.bounds 99 <| (Range.linearBounded () : Range<int>);;
val it : int * int = (-2147483648, 2147483647)
```

---

Here are two (related) parts from @jystic's talk on Hedgehog on the use of `Range` type and combinators:

1. [At 18:45](https://www.youtube.com/watch?v=AIv_9T0xKEo?t=1125) (watch up to 23:15)
2. [At 11:50](https://youtu.be/AIv_9T0xKEo?t=710) (watch up to 13:09)

(I'd watch them in that order because Range is actually introduced in `2.`, and then it's more obvious how it could be used in `1.` to prevent that bug that slipped in [box/text](https://github.com/bos/text) library.)
