### ISSUE TITLE
Throws OutOfMemoryException when using Bounded generators 

### ISSUE THREAD

**Issue by essic** [hedgehogqa/fsharp-hedgehog#178]
Hi.

First I'd like to thank you all for this library. 
Sadly I have an issue when using bounded generator. 
I have a test DLLs using .NETCore 2.2, where I use XUnit and Hedgehog, I noticed that when using Gen.LinearBounded() or Gen.ConstantBounded() my tests runs indefinitely. So I fired up a REPL to see what's going on, below the example :

```fsharp
#r "../../packages/test/Hedgehog/lib/netstandard1.6/Hedgehog.dll"
open Hedgehog


Gen.string (Range.linearBounded()) Gen.alphaNum
|> Gen.printSample
```

This throws :

```
--> Referenced 'C:\Users\cissea\shift-org\shift\Tools\Site24x7\src\Shift.Deploy24x7.ClientApi\../../packages/test/Hedgehog/lib/netstandard1.6/Hedgehog.dll'

System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at Microsoft.FSharp.Core.LanguagePrimitives.HashCompare.GenericComparisonWithComparerIntrinsic[T](IComparer comp, T x, T y)
   at Microsoft.FSharp.Core.LanguagePrimitives.HashCompare.GenericGreaterOrEqualIntrinsic[T](T x, T y)
   at Hedgehog.SeedModule.loop@136-12(Int64 genlo, BigInteger b, BigInteger magtgt, BigInteger mag, BigInteger v0, Seed seed0)
   at Hedgehog.SeedModule.nextBigInt(BigInteger lo, BigInteger hi, Seed seed)
   at Hedgehog.Gen.Char@361-4.Invoke(Seed seed, Int32 size)
   at Hedgehog.Random.map@39-2.Invoke(Seed seed, Int32 size)
   at Hedgehog.Random.map@39-2.Invoke(Seed seed, Int32 size)
   at Hedgehog.Tree.bind[a,b](Tree`1 _arg1, FSharpFunc`2 k)
   at Hedgehog.Gen.bindRandom@40.Invoke(Seed seed0, Int32 size)
   at Hedgehog.Random.loop@54-13[a](Random`1 r, Int32 size, Seed seed, Int32 k, FSharpList`1 acc)
   at Hedgehog.Random.replicate@53.Invoke(Seed seed0, Int32 size)
   at Hedgehog.Random.bind@45.Invoke(Seed seed, Int32 size)
   at Hedgehog.Random.map@39-2.Invoke(Seed seed, Int32 size)
   at Hedgehog.Random.map@39-2.Invoke(Seed seed, Int32 size)
   at Hedgehog.Random.loop@54-13[a](Random`1 r, Int32 size, Seed seed, Int32 k, FSharpList`1 acc)
   at Hedgehog.Random.replicate@53.Invoke(Seed seed0, Int32 size)
   at Hedgehog.Gen.PrintSample[a](Gen`1 g)
   at <StartupCode$FSI_0002>.$FSI_0002.main@()
Stopped due to error
```
I think that why I have infinite test running.
Do I misuse the feature or is there something going on ?

**Comment by moodmosaic** [comment]
Thanks for reporting this. I'm currently travelling but I should be able to take a look at this over the next few days.

**Comment by moodmosaic** [comment]
You shouldn't have to use bounded ranges in your test(s). In fact, I start thinking we shouldn't port them in the .NET/F# version because they just make it so easy to not do the right thing.

[Here's how the different types of Ranges work](https://www.youtube.com/watch?v=AIv_9T0xKEo&t=1254). — In your sample code, essentially you're generating strings of length in the full range of Int32 (up to 2,147,483,647) and `printSample` also has to shrink those.

Eventually, you're running OOM but I think that's different from https://github.com/hedgehogqa/fsharp-hedgehog/issues/177. Apart from the fact that they're part of the public API, may I ask why you use bounded ranges?

**Comment by essic** [comment]
I did not understood how it worked at all thanks for the video ! 

Basically my aim was to test a wide range of string included null & empty string. I want to be able to find edge cases as early as possible. That’s why I thought a larger set to shrink from could improve that bit of code, over time.

I realize now that I have some reading to do before I can do what I want...

Thanks again.

**Comment by moodmosaic** [comment]
Closing this, but absolutely feel free to reopen it, or add comments to it, if you need to. :rocket:
