### ISSUE TITLE
perfect minimal shrink test failing in master

### ISSUE THREAD

**Issue by bender2k14** [hedgehogqa/fsharp-hedgehog#201]
Is it the case that the test named `greedy traversal with a predicate yields the perfect minimal shrink` fails in the `master` branch?
https://github.com/hedgehogqa/fsharp-hedgehog/blob/6d1c5ff8581d9d1bda052e18d256e6469b134ddf/tests/Hedgehog.Tests/MinimalTests.fs#L65-L85

That test in the `master` branch fails for me.  One small caveat is that I am not so experienced with paket, so I first replaced paket with the normal NuGet package references that I am used to, and then experienced that test failing.

I found this failing test while working on a fix for #199, which is motivated by tests that started failing after being built with a newer version of MSBuild (from a newer version of the .NET Core SDK).  Maybe that could also explain why I am seeing a failing test in the `master` branch.

I debugged this test for quite a while and could share what I learned, but maybe everything I learned is already considered "known" and so not worth repeating.  I would find it very helpful if someone could give a quick reply like
- "That test passes for me, and it should pass for you too" or
- "That test fails for me too but I didn't know that until you pointed it out" or
- "That test fails for everyone and we already know why".

**Comment by moodmosaic** [comment]
Can you please re-run the test-suite from the command-line? Set the MSBuild verbosity level (`-v`) to normal (`n`) as in

```
dotnet test -v n tests/Hedgehog.Tests/Hedgehog.Tests.fsproj
```

---

On my machine ™

```
√ Hedgehog.Tests.MinimalTests.greedy traversal with a predicate yields the perfect minimal shrink [274ms]
```

**Comment by bender2k14** [comment]
Certainly.  Here is the [full output](https://github.com/hedgehogqa/fsharp-hedgehog/files/4863983/output.txt).  The relevant output is
```
...
  X Hedgehog.Tests.MinimalTests.greedy traversal with a predicate yields the perfect minimal shrink [27ms]
  Error Message:
   System.NullReferenceException : Object reference not set to an instance of an object.
  Stack Trace:
     at Microsoft.FSharp.Core.FSharpFunc`2.InvokeFast[V](FSharpFunc`2 func, T arg1, TResult arg2)
   at Hedgehog.Random.unsafeRun[a](Seed seed, Int32 size, Random`1 _arg1) in C:\Code\ThirdParty\fsharp-hedgehog\src\Hedgehog\Random.fs:line 12
   at Hedgehog.Random.map@40-1.Invoke(Seed seed, Int32 size) in C:\Code\ThirdParty\fsharp-hedgehog\src\Hedgehog\Random.fs:line 41
   at Hedgehog.Random.unsafeRun[a](Seed seed, Int32 size, Random`1 _arg1) in C:\Code\ThirdParty\fsharp-hedgehog\src\Hedgehog\Random.fs:line 12
   at Hedgehog.Random.run[a](Seed seed, Int32 size, Random`1 r) in C:\Code\ThirdParty\fsharp-hedgehog\src\Hedgehog\Random.fs:line 15
   at Hedgehog.Random.resize@80.Invoke(Seed seed, Int32 _arg1) in C:\Code\ThirdParty\fsharp-hedgehog\src\Hedgehog\Random.fs:line 81
   at Hedgehog.Random.unsafeRun[a](Seed seed, Int32 size, Random`1 _arg1) in C:\Code\ThirdParty\fsharp-hedgehog\src\Hedgehog\Random.fs:line 12
   at Hedgehog.Random.run[a](Seed seed, Int32 size, Random`1 r) in C:\Code\ThirdParty\fsharp-hedgehog\src\Hedgehog\Random.fs:line 15
   at Hedgehog.Gen.run@45T.Invoke(Seed seed, Random`1 random) in C:\Code\ThirdParty\fsharp-hedgehog\src\Hedgehog\Gen.fs:line 46
   at Hedgehog.Gen.bindRandom@41.Invoke(Seed seed0, Int32 size) in C:\Code\ThirdParty\fsharp-hedgehog\src\Hedgehog\Gen.fs:line 48
   at Hedgehog.Random.unsafeRun[a](Seed seed, Int32 size, Random`1 _arg1) in C:\Code\ThirdParty\fsharp-hedgehog\src\Hedgehog\Random.fs:line 12
   at Hedgehog.Random.delay@18.Invoke(Seed seed, Int32 size) in C:\Code\ThirdParty\fsharp-hedgehog\src\Hedgehog\Random.fs:line 19
   at Hedgehog.Random.unsafeRun[a](Seed seed, Int32 size, Random`1 _arg1) in C:\Code\ThirdParty\fsharp-hedgehog\src\Hedgehog\Random.fs:line 12
   at Hedgehog.Random.run[a](Seed seed, Int32 size, Random`1 r) in C:\Code\ThirdParty\fsharp-hedgehog\src\Hedgehog\Random.fs:line 15
   at Hedgehog.Property.loop@338-7.Invoke(Seed seed, Int32 size, Int32 tests, Int32 discards) in C:\Code\ThirdParty\fsharp-hedgehog\src\Hedgehog\Property.fs:line 348
   at Hedgehog.Property.Report(Int32 n, Property`1 p) in C:\Code\ThirdParty\fsharp-hedgehog\src\Hedgehog\Property.fs:line 361
   at Hedgehog.Property.Report(Property`1 p) in C:\Code\ThirdParty\fsharp-hedgehog\src\Hedgehog\Property.fs:line 365
   at Hedgehog.Property.Check(Property`1 p) in C:\Code\ThirdParty\fsharp-hedgehog\src\Hedgehog\Property.fs:line 376
   at Hedgehog.Tests.MinimalTests.greedy traversal with a predicate yields the perfect minimal shrink() in C:\Code\ThirdParty\fsharp-hedgehog\tests\Hedgehog.Tests\MinimalTests.fs:line 67
...

Test Run Failed.
Total tests: 182
     Passed: 181
     Failed: 1
...
```

**Comment by moodmosaic** [comment]
I wonder if this is an artifact related to the issue reported in #199

**Comment by bender2k14** [comment]
> I wonder if this is an artifact related to the issue reported in #199

I thought that too.  It could be a similar problem, but it is not the _exact_ same problem because that test fails for me when building the code with both .NET Core SDK versions 3.1.105 and 3.1.301.

**Comment by bender2k14** [comment]
That test fails for me when the code is built with any of the .NET Core SDKs that I happen to have installed, which are
- 2.1.202
- 2.1.403
- 2.1.802
- 2.2.402
- 3.0.100
- 3.1.105
- 3.1.301

and are all 64-bit.

**Comment by moodmosaic** [comment]
Unsure if that helps, but here's what I have on my local

```
>clrver

Microsoft (R) .NET CLR Version Tool  Version 4.8.3928.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Versions installed on the machine:
v4.0.30319
```

```
>gacutil /l ?

Microsoft (R) .NET Global Assembly Cache Utility.  Version 4.0.30319.0
Copyright (c) Microsoft Corporation.  All rights reserved.

The Global Assembly Cache contains the following assemblies:

Number of items = 0
```

```
>DotNetVersions.exe

Currently installed "classic" .NET Versions in the system:
4.0.0.0
4.8.03761
```

```
$ dotnet --list-sdks
2.1.802 [C:\Program Files\dotnet\sdk]
2.2.402 [C:\Program Files\dotnet\sdk]
3.1.301 [C:\Program Files\dotnet\sdk]
```

```
$ dotnet --list-runtimes
Microsoft.AspNetCore.All 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
Microsoft.AspNetCore.All 2.1.19 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
Microsoft.AspNetCore.All 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
Microsoft.AspNetCore.All 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
Microsoft.AspNetCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 2.1.19 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 3.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.NETCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 2.1.19 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 3.1.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.WindowsDesktop.App 3.1.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

**Comment by bender2k14** [comment]
I have an Azure DevOps organization (named "Tyson-Williams") containing a single project (named "Elmish WPF") that I use for situations like this: to build and test code on a system other than my own.  I built Hedgehog and ran its tests there.  I get the same result: that test is still failing.

Here are the [full logs](https://github.com/hedgehogqa/fsharp-hedgehog/files/4866546/azure_devops_logs.txt).  Here are some excerpts.
```
...
2020-07-02T20:18:13.8889132Z   X Hedgehog.Tests.MinimalTests.greedy traversal with a predicate yields the perfect minimal shrink [34ms]
2020-07-02T20:18:13.8906932Z   Error Message:
2020-07-02T20:18:13.8907730Z    System.NullReferenceException : Object reference not set to an instance of an object.
2020-07-02T20:18:13.8908368Z   Stack Trace:
2020-07-02T20:18:13.8908892Z      at Microsoft.FSharp.Core.FSharpFunc`2.InvokeFast[V](FSharpFunc`2 func, T arg1, TResult arg2)
2020-07-02T20:18:13.8909549Z    at Hedgehog.Random.map@40-1.Invoke(Seed seed, Int32 size) in d:\a\1\s\src\Hedgehog\Random.fs:line 41
2020-07-02T20:18:13.8910256Z    at Hedgehog.Gen.bindRandom@41.Invoke(Seed seed0, Int32 size) in d:\a\1\s\src\Hedgehog\Gen.fs:line 48
2020-07-02T20:18:13.8910996Z    at Hedgehog.Property.loop@338-7.Invoke(Seed seed, Int32 size, Int32 tests, Int32 discards) in d:\a\1\s\src\Hedgehog\Property.fs:line 348
2020-07-02T20:18:13.8911677Z    at Hedgehog.Property.Check(Property`1 p) in d:\a\1\s\src\Hedgehog\Property.fs:line 376
...
2020-07-02T20:18:15.2688194Z   X Hedgehog.Tests.MinimalTests.genExp is not its default value [521ms]
2020-07-02T20:18:15.2689768Z   Error Message:
2020-07-02T20:18:15.2690793Z    
2020-07-02T20:18:15.2691836Z MinimalTests.genExp |> MinimalTests.isDefaultGen |> not
2020-07-02T20:18:15.2692971Z Gen (Random null) |> MinimalTests.isDefaultGen |> not
2020-07-02T20:18:15.2693978Z true |> not
2020-07-02T20:18:15.2695353Z false
2020-07-02T20:18:15.2695866Z Expected: True
2020-07-02T20:18:15.2696261Z Actual:   False
2020-07-02T20:18:15.2712312Z   Stack Trace:
2020-07-02T20:18:15.2714044Z      at Hedgehog.Tests.MinimalTests.genExp is not its default value() in d:\a\1\s\tests\Hedgehog.Tests\MinimalTests.fs:line 81
...
2020-07-02T20:18:17.8611463Z Total tests: Unknown
2020-07-02T20:18:17.8611756Z      Passed: 183
2020-07-02T20:18:17.8611963Z      Failed: 2
...
```

The commit I tested includes the tests I am suggesting be added to `master` via PR #202.  I think the test named `greedy traversal with a predicate yields the perfect minimal shrink` is failing because `genExp` has its default value, which is exactly what the test 
named `genExp is not its default value` is intended to detect.

What about the idea of gating PRs by automated CI builds?  I have seen OSS projects use both [AppVeyor](https://www.appveyor.com/pricing/) and [Azure DevOps](https://azure.microsoft.com/en-us/pricing/details/devops/azure-devops-services/) for this purpose.

**Comment by moodmosaic** [comment]
Do you mean that #202 fails on the Azure DevOps? I haven't merged that yet but I'm planning to look into tomorrow.

**Comment by moodmosaic** [comment]
We could run each PR on both AppVeyor and Azure, we just need to set it up.

**Comment by bender2k14** [comment]
> Do you mean that #202 fails on the Azure DevOps? ... I'm planning to look into [that PR] tomorrow.

Yep.

It might sound a bit counterintuitive for me to suggest merging a failing test into `master`, but that is because I believe `master` already contains a failing test.  My claim is that the test I am suggesting be added fails for the same reason as the existing test in `master` but is significantly easier to understand why it fails.  (I spent many hours figuring out why the existing test in `master` is failing.)

I concluded the opening comment for that PR trying to express the same idea (i.e. why merging is a good idea even if the test fails) by saying
> It think it makes sense to merge this now before coming to a conclusion about issue #201. Either something about my development environment is broken, which is causing that test in the `master` branch to fail, and so these new tests also pass for everyone else. Or my development environment has identified a legitimate issue with that test, and so these new tests help to focus debugging efforts.

---

> I haven't merged [PR #202] yet but I'm planning to look into tomorrow.

No rush.  I will pause my investigation into the present issue until a decision has been made about the PR.

> We could run each PR on both AppVeyor and Azure, we just need to set it up.

Oh, I was probably unclear there.  I have only seen OSS projects use _either_ AppVeyor _or_ Azure DevOps.  (I corrected my comment above.)  I didn't mean to imply that Hedgehog should use both of them at the same time.  I think one would be sufficient.

Do you have a preference?

**Comment by moodmosaic** [comment]
Would that be possible with Travis CI? https://travis-ci.org/github/hedgehogqa/fsharp-hedgehog

**Comment by moodmosaic** [comment]
>No rush. I will pause my investigation into the present issue until a decision has been made about the PR.

I’m about to pull from master and run the tests on a totally new box. I’ll keep you posted.

**Comment by moodmosaic** [comment]
I still can't reproduce this 😢 Does it always fail for you or just [sometimes](http://xunitpatterns.com/Erratic%20Test.html)?

**Comment by bender2k14** [comment]
Since I have started paying close attention, I have only seen it fail.  It is possible that it once passed for me, but I can't say for sure.  I will keep a close eye on the potential causes of erratic tests.

**Comment by bender2k14** [comment]
Now that PR #202 has been merged, we can shift our focus from the test named `greedy traversal with a predicate yields the perfect minimal shrink` to the test named `genExp is not its default value`.

https://github.com/hedgehogqa/fsharp-hedgehog/blob/2a68ee22e85b5d9026b3b21a6a0a04bce9cef086/tests/Hedgehog.Tests/MinimalTests.fs#L82-L84

I will keep looking into why this test passes for @moodmosaic and builds on Travis CI but fails for me and my builds on Azure DevOps.

In the meantime, I have a hypothesis about one cause of the failure when it does occur.  The definition of `genExp` suppresses warning 40, which says
> Warning FS0040
This and other recursive references to the object(s) being defined will be checked for initialization-soundness at runtime through the use of a delayed reference. This is because you are defining one or more recursive objects, rather than recursive functions.

https://github.com/hedgehogqa/fsharp-hedgehog/blob/2a68ee22e85b5d9026b3b21a6a0a04bce9cef086/tests/Hedgehog.Tests/MinimalTests.fs#L53-L63

The test named `genExp is not its default value` is precisely checking for "initialization-soundness".  I briefly tried to change `genExp` into a function, but it just delayed the failure: instead of failing at the root node in that recursively defined data structure, it failed on a node at a depth of one.

**Comment by bender2k14** [comment]
> I will keep looking into why this test passes for @moodmosaic and builds on Travis CI but fails for me and my builds on Azure DevOps.

Yes!  I made progress on this.

> One small caveat is that I am not so experienced with paket, so I first replaced paket with the normal NuGet package references that I am used to, and then experienced that test failing.

I got all tests to pass on my machine after many changes...but the last one was picking the minimal versions of `FSharp.Core` just as paket was doing.

**Comment by bender2k14** [comment]
Quoting from https://github.com/hedgehogqa/fsharp-hedgehog/pull/207#issuecomment-655761938
> I found a different [workaround](https://github.com/hedgehogqa/fsharp-hedgehog/pull/207/commits/a598c7336494a127740e154fb5a16480d7121a8c) that I like, which is to move `expGen` into the test (and then I had to move `genName` as well).

I think this is a good workaround for this project.  I will create an issue in F#'s GitHub project about these values taking their default value when defined at the module level.

**Comment by moodmosaic** [comment]
Great job tracking down this issue :+1: :100:

**Comment by bender2k14** [comment]
> I will create an issue in F#'s GitHub project about these values taking their default value when defined at the module level.

That issue now exists: https://github.com/dotnet/fsharp/issues/9653

**Comment by moodmosaic** [comment]
>That issue now exists: https://github.com/dotnet/fsharp/issues/9653

:+1: (Twitter can sometimes help too, in case you want to tweet it, I'll make sure to RT from both hedgehogqa and my account.)
