### ISSUE TITLE
Regression in Gen.list

### ISSUE THREAD

**Issue by otto-gebb** [hedgehogqa/fsharp-hedgehog#241]
If one tries to generate a list with the length lower bound 2, shrinking fails with an exception.

Repro in fsi:

```
> #r "nuget:Hedgehog, 0.8.4";;
...

> open Hedgehog;;
> Gen.list (Range.linear 2 2) (Gen.constant 1) |> Gen.printSample ;;
=== Outcome ===
[1; 1]
=== Shrinks ===
> System.ArgumentException: The index is outside the legal range.
count = 1, distance past the list = 1
Parameter name: count
   at Microsoft.FSharp.Core.DetailedExceptions.invalidArgOutOfRange[?](String arg, Int32 index, String text, Int32 bound) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\local.fs:line 57
   at Microsoft.FSharp.Collections.ListModule.loop@474-29[a](Int32 count, Int32 i, FSharpList`1 lst) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\list.fs:line 477
   at Hedgehog.Gen.atLeast[a](Int32 n, FSharpList`1 xs)
   at Microsoft.FSharp.Collections.Internal.IEnumerator.next@193[T](FSharpFunc`2 f, IEnumerator`1 e, FSharpRef`1 started, Unit unitVar0) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\seq.fs:line 194
   at Microsoft.FSharp.Collections.Internal.IEnumerator.filter@188.System.Collections.IEnumerator.MoveNext() in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\seq.fs:line 196
   at Microsoft.FSharp.Collections.Internal.IEnumerator.map@75.DoMoveNext(b& curr) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\seq.fs:line 77
   at Microsoft.FSharp.Collections.Internal.IEnumerator.MapEnumerator`1.System.Collections.IEnumerator.MoveNext() in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\seq.fs:line 64
   at Hedgehog.Gen.PrintSample[a](Gen`1 g)
   at <StartupCode$FSI_0004>.$FSI_0004.main@()
Stopped due to error
```

The bug does not reproduce in v0.8.3.

**Comment by TysonMN** [comment]
I think this is a duplicate of issue #217, which was fixed in PR #231.  There hasn't been a release since that PR was merged.

**Comment by moodmosaic** [comment]
There should be a release coming up this week. I haven't got time to do it yet. (Also, time to start planning to automate the releases.)

**Comment by TysonMN** [comment]
> time to start planning to automate the releases.

I will help with that :)

**Comment by otto-gebb** [comment]
Closing as duplicate.
