### ISSUE TITLE
Flaky tests

### ISSUE THREAD

**Issue by adam-becker** [hedgehogqa/fsharp-hedgehog#283]
Some of our tests can fail randomly, to make CI more reliable we should address these.

```
X Hedgehog.Linq.Tests.LinqTests.CanUseWhereWithBool [28ms]
  Error Message:
   System.Exception : *** Gave up after 100 discards, passed 17 tests.
  Stack Trace:
     at Hedgehog.ReportModule.tryRaise(Report report) in D:\a\fsharp-hedgehog\fsharp-hedgehog\src\Hedgehog\Report.fs:line 107
   at Hedgehog.Linq.PropertyExtensions.Check(Property`1 property, Int32 tests) in D:\a\fsharp-hedgehog\fsharp-hedgehog\src\Hedgehog\Linq\Property.fs:line 106
   at Hedgehog.Linq.Tests.LinqTests.CanUseWhereWithBool() in D:\a\fsharp-hedgehog\fsharp-hedgehog\tests\Hedgehog.Linq.Tests\LinqTests.cs:line 104
```

The test above fails because it exhausted the allowed discards. The way to fix this would be to use a `Gen` to always gives us the data we want, and "filter" that to ensure that we can use `where`, as the test mandates.

/cc @moodmosaic @TysonMN

**Comment by moodmosaic** [comment]
Yep, we shouldn't have [erratic tests](http://xunitpatterns.com/Erratic%20Test.html) :+1:

**Comment by TysonMN** [comment]
@cmeeren described a similar issue in #154.  I provided a solution to his problem in PR https://github.com/hedgehogqa/fsharp-hedgehog-experimental/pull/42.  I suggest we remove our test flakiness by using the same approach.
