### ISSUE TITLE
Bug: `counterexample` breaks in presence of exceptions

### ISSUE THREAD

**Issue by AlexeyRaga** [hedgehogqa/fsharp-hedgehog#327]
Version: **0.10** from NuGet

It looks like when an exception is thrown inside of a property test, it works just fine unless there is a call to `counterexample`.

Here is the test:

```fsharp
[<Fact>]
let ``Test exceptions`` () =
    property {
        let! a = Gen.string (Range.linear 2 10) Gen.alphaNum
        
//        counterexample a
        Assert.Equal(a, "")
    } |> Property.check
```

with `counterexample` commented, it works as expected showing this output:

```
System.Exception: *** Failed! Falsifiable (after 1 test and 3 shrinks):

System.Exception
*** Failed! Falsifiable (after 1 test and 3 shrinks):
"aa"
Xunit.Sdk.EqualException: Assert.Equal() Failure
          ↓ (pos 0)
Expected: aa
Actual:   
          ↑ (pos 0)
   at Xunit.Assert.Equal(String expected, String actual, Boolean ignoreCase, Boolean ignoreLineEndingDifferences, Boolean ignoreWhiteSpaceDifferences) in C:\Dev\xunit\xunit\src\xunit.assert\Asserts\StringAsserts.cs:line 244
```

However, with `counterexample` uncommented it produces the following output:

```
Xunit.Sdk.EqualException
Assert.Equal() Failure
          ↓ (pos 0)
Expected: BB
Actual:   
          ↑ (pos 0)
   at Tests.Test exceptions@50-6.Invoke(String _arg2) in /Users/alexey/src/ep/connector-classroom/EP.Connector.Classroom.Tests/Tests.fs:line 50
   at Hedgehog.Property.bind@108-2.Invoke(a x)
   at Hedgehog.Property.bindGen@98.Invoke(Tuple`2 tupledArg)
   at Hedgehog.Gen.bind@44-1.Invoke(a x)
   at Hedgehog.Gen.bindRandom@41-1.Invoke(a x)
   at Hedgehog.Tree.bind[a,b](FSharpFunc`2 k, Tree`1 _arg1)
   at Hedgehog.Gen.bindRandom@34.Invoke(Seed seed0, Int32 size)
   at Hedgehog.Property.loop@168-11(Boolean renderRecheck, PropertyConfig config, Random`1 random, Seed seed, Int32 size, Int32 tests, Int32 discards)
   at Hedgehog.Property.reportWith'(Boolean renderRecheck, Int32 size0, Seed seed, PropertyConfig config, Property`1 p)
   at Hedgehog.Property.reportWith(PropertyConfig config, Property`1 p)
   at Hedgehog.Property.check(Property`1 p)
```

So as we can see, there is no `after N tests and K shrinks` message, the value is `BB` and not `aa` which suggests that shrinking has not even happened and, as it seems, the test just crashed.

`Assert.Equal` just throws and exception internally, so it can be replaced with `failwith` with the same result:

```fsharp
let ``Test exceptions`` () =
    property {
        let! a = Gen.string (Range.linear 2 10) Gen.alphaNum
        
        counterexample a
        failwith "boom!"
    } |> Property.check
```

Which probably means that when a function under test throws an exception Hedgehog may not work properly if `counterexample` is present in the test.

### Expected behaviour

I expect that test works with `counterexample` present the same way as it works without `counterexample` except, of course, `counterexample` printing the message.

**Comment by TysonMN** [comment]
Thanks for reporting this @AlexeyRaga.

Could you also create a GitHub repository containing your reproduction?

**Comment by AlexeyRaga** [comment]
@TysonMN sure, here it is: https://github.com/AlexeyRaga/FSharp.Hedgehog.Bugs

But really, it is just a copy/paste from the issue description

**Comment by TysonMN** [comment]
Thanks @AlexeyRaga.

I have never used `counterexample`.  What is it supposed to do?

**Comment by AlexeyRaga** [comment]
@TysonMN there is an official documentation here: https://hedgehogqa.github.io/fsharp-hedgehog/index.html#Custom-Operations

**Comment by TysonMN** [comment]
Thanks. I understand now. It is essentially just appending to the journal. I will take another look at this tomorrow.
