### ISSUE TITLE
Does Hedgehog return an incorrect value on failure?

### ISSUE THREAD

**Issue by AlexeyRaga** [hedgehogqa/fsharp-hedgehog#333]
I am running a test with a simple condition:

```fsharp
match message with
| Happy s when s.Reason.Contains('a') -> Nack
| _ -> Ack
```

I see in debug that it fails properly and the value is shrunk properly to the failure case of a single `a` character (see the screenshot)

![image](https://user-images.githubusercontent.com/1394391/131456018-79a9ad8a-42a4-4b29-ac3f-e74492d61268.png)

I also see in debug that this is the last shrink, i.e. the test is not getting called anymore.

However, the result of the test is printed as:

```
*** Failed! Falsifiable (after 68 tests and 6 shrinks):
[Happy { "reason": "`", "level": -287093 }]
```

Or see this screenshot
![image](https://user-images.githubusercontent.com/1394391/131456413-2ca8fcc9-93bd-4104-9e68-03243bf6bfbd.png)

Which is not a correct failing condition, it should say `"reason": "a"` instead!

Interestingly, I also have a numeric field in that structure, and when I do something like

```fsharp
| Happy s when s.Level = 97 -> Nack
```

Then the failure is reported correctly. So it looks like it is working for numbers, but not for strings

**Comment by AlexeyRaga** [comment]
Oh, there is more to that!
`a` is `97` and the backtick is `96`!

When I set my condition to be `s.Reason.Contains('b') -> Nack` then Hedgehog prints `a`. 
For `c` it prints `b`, etc.

Can it be that there is an `off-by-one` problem somewhere in reporting test results?

I also checked, and it seems like the value gets `ToString()`'d correctly, so it should not be the fault of the `ToString` implementation.

Somehow Hedgehog reports the wrong shrink?

**Comment by TysonMN** [comment]
Thanks for the report.  I will investigate this later today.

**Comment by TysonMN** [comment]
Can you share a complete test with the behavior you described?

**Comment by AlexeyRaga** [comment]
No, not the one where I see this behaviour, this is company's private codebase.

But I'll try to find time to make another one if you can't reproduce it otherwise.

**Comment by TysonMN** [comment]
`Hedgehog.Xunit` depends on `Hedgehog.Experimental` which depends on `Hedgehog`.  This is not a bug in `Hedgehog.Xunit` because of this reproduction.
```fsharp
type MyRecord =
    { String: string
      Int: int }

[<Fact>]
let ``test`` () =
  Property.check <| property {
    let! value = GenX.auto<MyRecord>
    let result = not (value.String.Contains('b'))
    Assert.True(result)
  }
```

```
  Message: 
System.Exception : *** Failed! Falsifiable (after 6 tests and 2 shrinks):
{ String = "a"
  Int = -3 }
Xunit.Sdk.TrueException: Assert.True() Failure
Expected: True
Actual:   False
   at Xunit.Assert.True(Nullable`1 condition, String userMessage) in C:\Dev\xunit\xunit\src\xunit.assert\Asserts\BooleanAsserts.cs:line 95
   at Xunit.Assert.True(Boolean condition) in C:\Dev\xunit\xunit\src\xunit.assert\Asserts\BooleanAsserts.cs:line 62
   at Tests.test@20-1.Invoke(MyRecord _arg1) in C:\Code\ThirdParty\fsharp-hedgehog\TestProject1\Tests.fs:line 21
   at Hedgehog.Property.prepend@115-1.Invoke(Unit _arg1)
This failure can be reproduced by running:
> Property.recheck (6 : Size) ({ Value = 5704476146548256008UL; Gamma = 6411217458561276937UL }) <property>
```

My currently feeling is that this is a bug in `Hedgehog.Experimental`, but I could be wrong.

**Comment by TysonMN** [comment]
Another thing that is wrong about this is that the `int` value is different every time.

**Comment by TysonMN** [comment]
The generators `Hedgehog.Experimental` uses for `string` and `int` are [`Gen.string (Range.linear 0 50) Gen.latin1`](https://github.com/hedgehogqa/fsharp-hedgehog-experimental/blob/439159cd7cbf99b793bae3eac59dd02a9192d7a8/src/Hedgehog.Experimental/Gen.fs#L376) and [`Gen.int <| Range.exponentialBounded ()`](https://github.com/hedgehogqa/fsharp-hedgehog-experimental/blob/439159cd7cbf99b793bae3eac59dd02a9192d7a8/src/Hedgehog.Experimental/Gen.fs#L366) respectively.  If I manually create a `MyRecord` generator, then the shrunken value is consistently `{ String = "b"; Int = 0 }`, which is correct.  I think the bug is in the `auto` function from `Hedgehog.Experimental`.

**Comment by TysonMN** [comment]
@moodmosaic, can you transfer this issue to [fsharp-hedgehog-experimental](https://github.com/hedgehogqa/fsharp-hedgehog-experimental)?

**Comment by TysonMN** [comment]
Here is a test that currently fails but would pass if this bug didn't exist.
```fsharp
type MyRecord =
  { String: string
    Int: int }

[<Fact>]
let ``auto of record shrinks properly`` () =
  let property = property {
    let! value = GenX.auto<MyRecord>
    test <@ not (value.String.Contains('b')) @>
  }
  let report = Property.report property
  let rendered = Report.render report
  test <@ rendered.Contains "{String = \"b\";\n Int = 0;}" @>
```

**Comment by TysonMN** [comment]
Actually, maybe this isn't technically a bug in `Hedgehog.Experimental`.

[`Hedgehog.Experimental` mutates in the `gen` computational expression when generating a record instance](https://github.com/hedgehogqa/fsharp-hedgehog-experimental/blob/439159cd7cbf99b793bae3eac59dd02a9192d7a8/src/Hedgehog.Experimental/Gen.fs#L471-L482)...
```fsharp
| Shape.FSharpRecord (:? ShapeFSharpRecord<'a> as shape) ->
    let fieldGen =
      shape.Fields
      |> Array.map mkRandomMember

    gen {
      let mutable target = shape.CreateUninitialized ()
      for eg in fieldGen do
        let! u = eg
        target <- u target
      return target
    }
```

...but we already know that Hedgehog doesn't shrink correctly when generators involve mutation (c.f. #192).

I rewrote that code without mutation, and now my test passes.  There is a bunch more mutation in that `auto` function.  I will remove all of it and then create a PR.

**Comment by TysonMN** [comment]
Here is the PR https://github.com/hedgehogqa/fsharp-hedgehog-experimental/pull/51
